name: fotobox_frontend
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animated_countdown: ^0.0.3
  camera: ^0.11.0+1
  camera_windows: ^0.2.5
  circular_countdown_timer: ^0.2.3
  download: ^1.0.0
  flutter:
    sdk: flutter
  flutter_command: ^5.0.0+20
  flutter_guid: ^0.3.1
  flutter_localizations:
    sdk: flutter
  get_it: ^7.7.0
  http: ^1.2.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  pretty_qr_code: ^3.3.0
  watch_it: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/textfiles/
